# Generated by Django 5.0.6 on 2025-12-28 04:45

import accounts.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-registration_date'], 'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AddField(
            model_name='user',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('birth_date', models.DateField(verbose_name='Data de Nascimento')),
                ('photo', models.ImageField(upload_to='profiles/photos/', validators=[accounts.models.validate_image_extension, accounts.models.validate_image_size], verbose_name='Foto 3x4')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(max_length=20, verbose_name='RG')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('address', models.CharField(max_length=255, verbose_name='Endereço')),
                ('address_number', models.CharField(max_length=10, verbose_name='Número')),
                ('address_complement', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.CharField(choices=[('secretaria', 'Secretaria'), ('financeiro', 'Financeiro'), ('atendimento', 'Atendimento'), ('administrativo', 'Administrativo'), ('rh', 'Recursos Humanos'), ('outro', 'Outro')], max_length=50, verbose_name='Departamento')),
                ('position', models.CharField(max_length=100, verbose_name='Cargo')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('ferias', 'Férias'), ('afastado', 'Afastado'), ('licenca', 'Licença')], default='ativo', max_length=20, verbose_name='Status')),
                ('hire_date', models.DateField(auto_now_add=True, verbose_name='Data de Contratação')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salário')),
                ('observation', models.TextField(blank=True, verbose_name='Observações')),
                ('support_document_1', models.FileField(blank=True, null=True, upload_to='employees/documents/', validators=[accounts.models.validate_document_extension, accounts.models.validate_document_size], verbose_name='Documento de Suporte 1')),
                ('support_document_2', models.FileField(blank=True, null=True, upload_to='employees/documents/', validators=[accounts.models.validate_document_extension, accounts.models.validate_document_size], verbose_name='Documento de Suporte 2')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Funcionário',
                'verbose_name_plural': 'Perfis de Funcionários',
            },
        ),
        migrations.CreateModel(
            name='InstructorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('birth_date', models.DateField(verbose_name='Data de Nascimento')),
                ('photo', models.ImageField(upload_to='profiles/photos/', validators=[accounts.models.validate_image_extension, accounts.models.validate_image_size], verbose_name='Foto 3x4')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(max_length=20, verbose_name='RG')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('address', models.CharField(max_length=255, verbose_name='Endereço')),
                ('address_number', models.CharField(max_length=10, verbose_name='Número')),
                ('address_complement', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cnh', models.CharField(max_length=30, verbose_name='Número da CNH')),
                ('cnh_emission_date', models.DateField(verbose_name='Data de Emissão da CNH')),
                ('cnh_document', models.FileField(upload_to='instructors/cnh/', validators=[accounts.models.validate_document_extension, accounts.models.validate_document_size], verbose_name='CNH (Frente e Verso)')),
                ('credential', models.CharField(max_length=100, unique=True, verbose_name='Credencial de Instrutor')),
                ('support_document_1', models.FileField(blank=True, null=True, upload_to='instructors/documents/', validators=[accounts.models.validate_document_extension, accounts.models.validate_document_size], verbose_name='Documento de Suporte 1')),
                ('support_document_2', models.FileField(blank=True, null=True, upload_to='instructors/documents/', validators=[accounts.models.validate_document_extension, accounts.models.validate_document_size], verbose_name='Documento de Suporte 2')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('pendente', 'Pendente Aprovação'), ('suspenso', 'Suspenso')], default='pendente', max_length=20, verbose_name='Status')),
                ('rating', models.FloatField(default=0.0, help_text='Avaliação média do instrutor (0-5)', verbose_name='Avaliação')),
                ('total_students', models.IntegerField(default=0, verbose_name='Total de Alunos')),
                ('total_lessons', models.IntegerField(default=0, verbose_name='Total de Aulas Ministradas')),
                ('hire_date', models.DateField(auto_now_add=True, verbose_name='Data de Contratação')),
                ('observation', models.TextField(blank=True, verbose_name='Observações')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Instrutor',
                'verbose_name_plural': 'Perfis de Instrutores',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('birth_date', models.DateField(verbose_name='Data de Nascimento')),
                ('photo', models.ImageField(upload_to='profiles/photos/', validators=[accounts.models.validate_image_extension, accounts.models.validate_image_size], verbose_name='Foto 3x4')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(max_length=20, verbose_name='RG')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('address', models.CharField(max_length=255, verbose_name='Endereço')),
                ('address_number', models.CharField(max_length=10, verbose_name='Número')),
                ('address_complement', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('pendente', 'Pendente'), ('suspenso', 'Suspenso')], default='ativo', max_length=20, verbose_name='Status')),
                ('progress', models.IntegerField(default=0, help_text='Progresso do aluno em porcentagem', verbose_name='Progresso (%)')),
                ('total_lessons', models.IntegerField(default=0, verbose_name='Total de Aulas')),
                ('completed_lessons', models.IntegerField(default=0, verbose_name='Aulas Concluídas')),
                ('enrollment_date', models.DateField(auto_now_add=True, verbose_name='Data de Matrícula')),
                ('observation', models.TextField(blank=True, verbose_name='Observações')),
                ('support_document_1', models.FileField(blank=True, null=True, upload_to='students/documents/', validators=[accounts.models.validate_document_extension, accounts.models.validate_document_size], verbose_name='Documento de Suporte 1')),
                ('support_document_2', models.FileField(blank=True, null=True, upload_to='students/documents/', validators=[accounts.models.validate_document_extension, accounts.models.validate_document_size], verbose_name='Documento de Suporte 2')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Aluno',
                'verbose_name_plural': 'Perfis de Alunos',
            },
        ),
    ]
