# Generated by Django 6.0 on 2025-12-29 01:00

import accounts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_user_registration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='photo',
            field=models.ImageField(upload_to=accounts.models.upload_profile_photo, validators=[accounts.models.validate_image_extension, accounts.models.validate_image_size], verbose_name='Foto 3x4'),
        ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='photo',
            field=models.ImageField(upload_to=accounts.models.upload_profile_photo, validators=[accounts.models.validate_image_extension, accounts.models.validate_image_size], verbose_name='Foto 3x4'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='photo',
            field=models.ImageField(upload_to=accounts.models.upload_profile_photo, validators=[accounts.models.validate_image_extension, accounts.models.validate_image_size], verbose_name='Foto 3x4'),
        ),
        migrations.CreateModel(
            name='InstructorVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=10, verbose_name='Placa')),
                ('renavam', models.CharField(max_length=11, verbose_name='RENAVAM')),
                ('model', models.CharField(max_length=100, verbose_name='Modelo')),
                ('make', models.CharField(max_length=100, verbose_name='Marca')),
                ('color', models.CharField(max_length=50, verbose_name='Cor')),
                ('year', models.PositiveIntegerField(verbose_name='Ano')),
                ('dual_control', models.BooleanField(default=False, verbose_name='Acionamento Duplo')),
                ('adapted_pcd', models.BooleanField(default=False, verbose_name='Adaptado para PCD')),
                ('instructor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='accounts.instructorprofile', verbose_name='Instrutor')),
            ],
            options={
                'verbose_name': 'Veículo do Instrutor',
                'verbose_name_plural': 'Veículos dos Instrutores',
            },
        ),
    ]
