# Generated by Django 6.0 on 2025-12-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_employeeprofile_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='cep_base',
            field=models.CharField(blank=True, help_text='CEP onde o instrutor inicia as aulas', max_length=9, verbose_name='CEP da Base/Garagem'),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, verbose_name='Gênero'),
        ),
    ]
