# Generated by Django 6.0 on 2025-12-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_instructorprofile_cep_base_instructorprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='gender_identity',
            field=models.CharField(blank=True, choices=[('CF', 'Cisgênero Feminino'), ('CM', 'Cisgênero Masculino'), ('TM', 'Homem Transgênero'), ('TW', 'Mulher Transgênero')], help_text='Usado para exibir e preferências; mapeado para Homem/Mulher.', max_length=2, verbose_name='Identidade de gênero'),
        ),
    ]
