# Generated by Django 6.0 on 2025-12-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_instructorprofile_gender_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='gender_identity',
            field=models.CharField(blank=True, choices=[('CF', 'Cisgênero Feminino'), ('CM', 'Cisgênero Masculino'), ('TM', 'Homem Transgênero'), ('TW', 'Mulher Transgênero')], help_text='Informação de identidade de gênero do aluno', max_length=2, verbose_name='Identidade de gênero'),
        ),
    ]
