# Generated by Django 6.0 on 2025-12-29 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_studentprofile_gender_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='vehicle_categories',
            field=models.CharField(choices=[('A', 'Categoria A - Motocicleta'), ('B', 'Categoria B - Carro'), ('AB', 'Ambas as categorias')], default='B', help_text='Qual(is) categoria(s) de veículo o instrutor trabalha', max_length=2, verbose_name='Categorias de Veículo'),
        ),
    ]
