# Generated by Django 6.0 on 2025-12-29 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_instructorprofile_vehicle_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='license_categories',
            field=models.CharField(choices=[('A', 'Categoria A - Motocicleta'), ('B', 'Categoria B - Carro'), ('AB', 'Ambas as categorias')], default='B', help_text='Qual(is) categoria(s) de CNH o aluno está tirar', max_length=2, verbose_name='Categoria(s) de CNH'),
        ),
    ]
