# Generated by Django 6.0 on 2026-01-07 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_instructorvehicle_last_license_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorvehicle',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='accounts.instructorprofile', verbose_name='Instrutor'),
        ),
        migrations.AlterUniqueTogether(
            name='instructorvehicle',
            unique_together={('instructor', 'plate')},
        ),
    ]
