# Generated by Django 5.0.6 on 2025-12-28 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('duration', models.IntegerField(default=50, help_text='Duração em minutos')),
                ('location', models.CharField(max_length=255)),
                ('vehicle_type', models.CharField(choices=[('A', 'Categoria A - Motocicleta'), ('B', 'Categoria B - Carro'), ('D', 'Categoria D - Ônibus')], max_length=1)),
                ('status', models.CharField(choices=[('scheduled', 'Agendada'), ('in-progress', 'Em Andamento'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='scheduled', max_length=20)),
                ('score', models.CharField(blank=True, help_text='Avaliação da aula', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('lesson_number', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(limit_choices_to={'role': 'instrutor'}, on_delete=django.db.models.deletion.CASCADE, related_name='instructor_lessons', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'aluno'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_lessons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(choices=[('baliza', 'Baliza'), ('estacionamento', 'Estacionamento'), ('direcao_via', 'Direção em via'), ('conversoes', 'Conversões'), ('ladeira', 'Ladeira')], max_length=50)),
                ('progress', models.IntegerField(default=0, help_text='Progresso de 0 a 100')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'aluno'}, on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progresso do Aluno',
                'verbose_name_plural': 'Progressos dos Alunos',
                'unique_together': {('student', 'skill')},
            },
        ),
    ]
