# Generated by Django 6.0 on 2025-12-28 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentProgress',
        ),
    ]
