# Generated by Django 6.0 on 2025-12-29 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_employeeprofile_photo_and_more'),
        ('lessons', '0002_delete_studentprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='prefer_adapted_pcd',
            field=models.BooleanField(default=False, verbose_name='Preferência: Adaptado PCD'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='prefer_dual_control',
            field=models.BooleanField(default=False, verbose_name='Preferência: Acionamento Duplo'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='accounts.instructorvehicle', verbose_name='Veículo'),
        ),
    ]
