# Generated by Django 6.0 on 2025-12-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_lesson_prefer_adapted_pcd_lesson_prefer_dual_control_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='cep',
            field=models.CharField(blank=True, max_length=9, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='estado',
            field=models.CharField(blank=True, max_length=2, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='numero',
            field=models.CharField(default=1, max_length=10, verbose_name='Número'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='rua',
            field=models.CharField(blank=True, max_length=255, verbose_name='Rua'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
