# Generated by Django 6.0 on 2025-12-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_lesson_bairro_lesson_cep_lesson_cidade_lesson_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='student_feedback',
            field=models.TextField(blank=True, help_text='Comentário do aluno sobre a aula', verbose_name='Feedback do Aluno'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='student_rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Nota de 1 a 5 estrelas dada pelo aluno', max_digits=2, null=True, verbose_name='Avaliação do Aluno'),
        ),
    ]
