# Generated by Django 6.0 on 2025-12-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_lesson_student_feedback_lesson_student_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente de Confirmação'), ('scheduled', 'Agendada'), ('in-progress', 'Em Andamento'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='pending', max_length=20),
        ),
    ]
