# Generated by Django 6.0 on 2025-12-30 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_alter_lesson_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente de Confirmação'), ('scheduled', 'Agendada'), ('in-progress', 'Em Andamento'), ('completed', 'Completada'), ('cancelled', 'Cancelada'), ('rescheduled', 'Remarcada')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='vehicle_type',
            field=models.CharField(choices=[('A', 'Categoria A - Motocicleta'), ('B', 'Categoria B - Carro')], max_length=1),
        ),
    ]
