# Generated by Django 6.0 on 2025-12-31 01:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_alter_lesson_status_alter_lesson_vehicle_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='instructor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'instrutor'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructor_lessons', to=settings.AUTH_USER_MODEL, verbose_name='Instrutor'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('A', 'Categoria A - Motocicleta'), ('B', 'Categoria B - Carro')], max_length=1, null=True, verbose_name='Tipo de Veículo'),
        ),
    ]
